/* Generated by scripts/build-cases-catalog.mjs — do not edit by hand */
import type { CSSProperties } from "react";

export type CaseIndexCategory =
  | "real-estate"
  | "education"
  | "ecommerce"
  | "services"
  | "shipping"
  | "retail"
  | "food"
  | "print";

export type MetricColor = "green" | "purple" | "amber" | "coral";

export type CoverShape = {
  background: string;
  top?: string;
  right?: string;
  bottom?: string;
  left?: string;
  width?: string;
  height?: string;
};

export type CaseStudyDetail = {
  kicker: string;
  title: string;
  background: string;
  challenges: string[];
  flow: string[];
  tags: string[];
  metrics: { value: string; label: string; color: MetricColor }[];
};

export type CaseIndexCard = {
  id: string;
  category: CaseIndexCategory;
  featuredWhenAll?: boolean;
  industryLabel: string;
  industryBadgeClass: string;
  listTitle: string;
  listExcerpt: string;
  metrics: { value: string; label: string; color: MetricColor }[];
  tags: string[];
  logoInitials: string;
  logoStyle: CSSProperties;
  coverImage: string;
  coverBg?: string;
  coverShapes: CoverShape[];
};

export type CaseStudy = CaseIndexCard & { detail: CaseStudyDetail };

export const caseIndexCards: CaseIndexCard[] = [
  {
    id: "blue-arrow",
    category: "real-estate",
    featuredWhenAll: true,
    industryLabel: "Real Estate",
    industryBadgeClass: "badge-real-estate",
    listTitle: "How a real estate firm closed 3x more property deals with an AI sales agent that never sleeps",
    listExcerpt: "A WhatsApp AI agent qualifies leads by budget and interest, presents property cards, and books site visits automatically — cutting manual follow-up by 70%.",
    metrics: [
      {
        value: "↑ 68%",
        label: "Lead response rate",
        color: "green"
      },
      {
        value: "70%",
        label: "Less manual follow-up",
        color: "amber"
      }
    ],
    tags: [
      "WhatsApp",
      "Lead Qual.",
      "GPT-4.1"
    ],
    logoInitials: "BA",
    logoStyle: {
      background: "rgba(59,130,246,.2)",
      border: "1px solid rgba(59,130,246,.35)"
    },
    coverImage: "/cases/covers/blue-arrow.jpg",
    coverBg: "linear-gradient(135deg,#0f1f3d,#1a3a6b,#0f2744)",
    coverShapes: [
      {
        background: "#3B82F6",
        top: "-50px",
        right: "60px",
        width: "160px",
        height: "160px"
      }
    ]
  },
  {
    id: "itshare",
    category: "education",
    featuredWhenAll: false,
    industryLabel: "Education",
    industryBadgeClass: "badge-education",
    listTitle: "AI enrollment agent handling 200+ daily inquiries across 3 branches",
    listExcerpt: "A bilingual AI agent answers course questions, shares branch schedules, and captures student leads 24/7 — with zero branch schedule mixing.",
    metrics: [
      {
        value: "200+",
        label: "Daily inquiries",
        color: "purple"
      },
      {
        value: "↑ 45%",
        label: "Lead capture rate",
        color: "green"
      }
    ],
    tags: [
      "WhatsApp",
      "Enrollment",
      "Arabic AI"
    ],
    logoInitials: "IT",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/itshare.jpg",
    coverBg: "linear-gradient(135deg,#1a0a2e,#2d1554,#1a0a2e)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-20px",
        right: "30px",
        width: "120px",
        height: "120px"
      }
    ]
  },
  {
    id: "givari",
    category: "ecommerce",
    featuredWhenAll: false,
    industryLabel: "eCommerce",
    industryBadgeClass: "badge-ecommerce",
    listTitle: "Dual-agent fashion bot with WooCommerce and vision-based product lookup",
    listExcerpt: "Customers send a photo — the AI identifies the item, pulls it from the store catalog, and completes the order inside WhatsApp.",
    metrics: [
      {
        value: "↑ 55%",
        label: "Orders via WhatsApp",
        color: "green"
      },
      {
        value: "0",
        label: "Manual lookups",
        color: "amber"
      }
    ],
    tags: [
      "WooCommerce",
      "Vision AI",
      "Dual Agent"
    ],
    logoInitials: "GV",
    logoStyle: {
      background: "rgba(216,90,48,.2)",
      border: "1px solid rgba(216,90,48,.35)"
    },
    coverImage: "/cases/covers/givari.jpg",
    coverBg: "linear-gradient(135deg,#1f0a0a,#3d1212,#2a0d0d)",
    coverShapes: [
      {
        background: "#D85A30",
        top: "-30px",
        left: "50px",
        width: "130px",
        height: "130px"
      }
    ]
  },
  {
    id: "waseem",
    category: "services",
    featuredWhenAll: false,
    industryLabel: "ISP / Services",
    industryBadgeClass: "badge-services",
    listTitle: "Separate AI agents for sales and technical support — one number, two brains",
    listExcerpt: "A dual-agent system routes customers between sales and support — eliminating crossed conversations and misrouted tickets.",
    metrics: [
      {
        value: "80%",
        label: "Support auto-resolved",
        color: "green"
      },
      {
        value: "↑ 40%",
        label: "Upsell conversion",
        color: "purple"
      }
    ],
    tags: [
      "Dual Agent",
      "Support Bot",
      "Routing"
    ],
    logoInitials: "WN",
    logoStyle: {
      background: "rgba(29,158,117,.2)",
      border: "1px solid rgba(29,158,117,.35)"
    },
    coverImage: "/cases/covers/waseem.jpg",
    coverBg: "linear-gradient(135deg,#0a1a0f,#0f3320,#0a1a12)",
    coverShapes: [
      {
        background: "#1D9E75",
        top: "-15px",
        right: "50px",
        width: "100px",
        height: "100px"
      }
    ]
  },
  {
    id: "sultan",
    category: "shipping",
    featuredWhenAll: false,
    industryLabel: "Shipping",
    industryBadgeClass: "badge-shipping",
    listTitle: "Automated order intake — inquiry to shipment booking in under 2 minutes",
    listExcerpt: "The AI collects shipment details, calculates costs, confirms orders, and logs everything to a central sheet — removing manual back-and-forth from dispatch.",
    metrics: [
      {
        value: "↓ 85%",
        label: "Manual data entry",
        color: "amber"
      },
      {
        value: "<2 min",
        label: "Booking time",
        color: "green"
      }
    ],
    tags: [
      "Order Processing",
      "Sheets Sync"
    ],
    logoInitials: "SB",
    logoStyle: {
      background: "rgba(239,159,39,.2)",
      border: "1px solid rgba(239,159,39,.35)"
    },
    coverImage: "/cases/covers/sultan.jpg",
    coverBg: "linear-gradient(135deg,#1a1000,#3d2a00,#1f1500)",
    coverShapes: [
      {
        background: "#EF9F27",
        right: "30px",
        bottom: "-30px",
        width: "120px",
        height: "120px"
      }
    ]
  },
  {
    id: "rz-estate",
    category: "real-estate",
    featuredWhenAll: true,
    industryLabel: "Real Estate",
    industryBadgeClass: "badge-real-estate",
    listTitle: "Trilingual AI agent converting international property inquiries 24/7",
    listExcerpt: "The bot detects Arabic, Kurdish Sorani, or English automatically, qualifies leads by property type and budget, and hands off warm prospects.",
    metrics: [
      {
        value: "3 langs",
        label: "AR · Sorani · EN",
        color: "purple"
      },
      {
        value: "↑ 60%",
        label: "Intl. lead conversion",
        color: "green"
      }
    ],
    tags: [
      "Multilingual",
      "Lead Routing",
      "Kurdish Sorani"
    ],
    logoInitials: "RZ",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/rz-estate.jpg",
    coverBg: "linear-gradient(135deg,#0a0a1a,#1a1a3d,#0f0f2a)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-40px",
        left: "80px",
        width: "150px",
        height: "150px"
      },
      {
        background: "#D85A30",
        right: "40px",
        bottom: "-10px",
        width: "80px",
        height: "80px"
      }
    ]
  },
  {
    id: "mimi",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Fashion Retail",
    industryBadgeClass: "badge-retail",
    listTitle: "AI shopping assistant that boosted repeat purchase rate for a fashion brand",
    listExcerpt: "The bot greets returning customers, recommends from order history, and handles size inquiries — a personalized WhatsApp shopping experience.",
    metrics: [
      {
        value: "↑ 38%",
        label: "Repeat purchase",
        color: "green"
      },
      {
        value: "92%",
        label: "CSAT score",
        color: "amber"
      }
    ],
    tags: [
      "Fashion Bot",
      "Personalization"
    ],
    logoInitials: "MM",
    logoStyle: {
      background: "rgba(216,90,48,.2)",
      border: "1px solid rgba(216,90,48,.35)"
    },
    coverImage: "/cases/covers/mimi.jpg",
    coverBg: "linear-gradient(135deg,#1a0f2e,#2d1a4a,#1a0f2e)",
    coverShapes: [
      {
        background: "#D85A30",
        top: "-15px",
        right: "40px",
        width: "100px",
        height: "100px"
      }
    ]
  },
  {
    id: "dr-ihab",
    category: "services",
    featuredWhenAll: false,
    industryLabel: "Healthcare",
    industryBadgeClass: "badge-healthcare",
    listTitle: "Appointment booking bot that cut front-desk calls by 60% for an orthopedic clinic",
    listExcerpt: "Patients book, reschedule, or cancel via WhatsApp — the bot checks real-time availability and sends Arabic confirmations automatically.",
    metrics: [
      {
        value: "↓ 60%",
        label: "Front-desk calls",
        color: "green"
      },
      {
        value: "24/7",
        label: "Booking availability",
        color: "purple"
      }
    ],
    tags: [
      "Appointment Bot",
      "Healthcare",
      "Arabic"
    ],
    logoInitials: "IY",
    logoStyle: {
      background: "rgba(29,158,117,.2)",
      border: "1px solid rgba(29,158,117,.35)"
    },
    coverImage: "/cases/covers/dr-ihab.jpg",
    coverBg: "linear-gradient(135deg,#0a1a10,#0f2e1a,#0a1a10)",
    coverShapes: [
      {
        background: "#1D9E75",
        top: "-20px",
        left: "60px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "panda",
    category: "ecommerce",
    featuredWhenAll: false,
    industryLabel: "eCommerce",
    industryBadgeClass: "badge-ecommerce",
    listTitle: "AI product advisor that cut support tickets by 50% for a tech accessories store",
    listExcerpt: "The agent handles compatibility questions, recommends accessories by device model, and processes orders — no human needed for most conversations.",
    metrics: [
      {
        value: "↓ 50%",
        label: "Support tickets",
        color: "green"
      },
      {
        value: "80%",
        label: "Fully automated",
        color: "amber"
      }
    ],
    tags: [
      "Product Advisor",
      "Order Bot"
    ],
    logoInitials: "PP",
    logoStyle: {
      background: "rgba(29,158,117,.2)",
      border: "1px solid rgba(29,158,117,.35)"
    },
    coverImage: "/cases/covers/panda.jpg",
    coverBg: "linear-gradient(135deg,#0f1a10,#1a3020,#0f1a10)",
    coverShapes: [
      {
        background: "#1D9E75",
        top: "-15px",
        right: "40px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "villa",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Retail",
    industryBadgeClass: "badge-retail",
    listTitle: "Conversational sales agent that made WhatsApp the top revenue channel",
    listExcerpt: "A warm Iraqi Arabic sales agent presents product lines, handles pricing questions, and guides customers to purchase.",
    metrics: [
      {
        value: "↑ 42%",
        label: "WhatsApp revenue",
        color: "amber"
      },
      {
        value: "3 min",
        label: "Avg. close time",
        color: "green"
      }
    ],
    tags: [
      "Sales Agent",
      "Iraqi Arabic"
    ],
    logoInitials: "VG",
    logoStyle: {
      background: "rgba(239,159,39,.2)",
      border: "1px solid rgba(239,159,39,.35)"
    },
    coverImage: "/cases/covers/villa.jpg",
    coverBg: "linear-gradient(135deg,#1a100a,#3a2010,#1a100a)",
    coverShapes: [
      {
        background: "#EF9F27",
        top: "-20px",
        left: "50px",
        width: "120px",
        height: "120px"
      }
    ]
  },
  {
    id: "noor",
    category: "print",
    featuredWhenAll: false,
    industryLabel: "Print & Media",
    industryBadgeClass: "badge-print",
    listTitle: "Curriculum book sales bot — 300+ school orders in peak season, zero errors",
    listExcerpt: "The bot guides teachers and parents through grade-specific book bundles, confirms orders, and coordinates pickup — all via WhatsApp.",
    metrics: [
      {
        value: "300+",
        label: "Peak season orders",
        color: "purple"
      },
      {
        value: "0",
        label: "Order entry errors",
        color: "green"
      }
    ],
    tags: [
      "Order Bot",
      "Seasonal Scale"
    ],
    logoInitials: "NP",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/noor.jpg",
    coverBg: "linear-gradient(135deg,#0a0f1a,#101a30,#0a0f1a)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-15px",
        right: "50px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "fofa",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Fashion Retail",
    industryBadgeClass: "badge-retail",
    listTitle: "One AI agent managing two fashion brands from a single WhatsApp number",
    listExcerpt: "One agent routes customers to the right brand, handles sizing, and processes orders — with consistent Arabic tone across both.",
    metrics: [
      {
        value: "2 brands",
        label: "One WhatsApp #",
        color: "purple"
      },
      {
        value: "↑ 33%",
        label: "Cross-brand sales",
        color: "green"
      }
    ],
    tags: [
      "Multi-Brand",
      "Fashion Bot"
    ],
    logoInitials: "FS",
    logoStyle: {
      background: "rgba(216,90,48,.2)",
      border: "1px solid rgba(216,90,48,.35)"
    },
    coverImage: "/cases/covers/fofa.jpg",
    coverBg: "linear-gradient(135deg,#1a0a18,#30103a,#1a0a18)",
    coverShapes: [
      {
        background: "#D85A30",
        top: "-20px",
        right: "50px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "amcupcakes",
    category: "food",
    featuredWhenAll: false,
    industryLabel: "Food & Bakery",
    industryBadgeClass: "badge-food",
    listTitle: "WhatsApp ordering bot that doubled weekend capacity and eliminated phone orders",
    listExcerpt: "Customers browse the menu, customize orders, and confirm payment — all inside WhatsApp, with zero phone calls needed.",
    metrics: [
      {
        value: "↑ 2x",
        label: "Weekend capacity",
        color: "coral"
      },
      {
        value: "0",
        label: "Phone orders needed",
        color: "green"
      }
    ],
    tags: [
      "Food Ordering",
      "WhatsApp",
      "Egypt"
    ],
    logoInitials: "AM",
    logoStyle: {
      background: "rgba(216,90,48,.2)",
      border: "1px solid rgba(216,90,48,.35)"
    },
    coverImage: "/cases/covers/amcupcakes.jpg",
    coverBg: "linear-gradient(135deg,#1a080a,#380f15,#1a080a)",
    coverShapes: [
      {
        background: "#D85A30",
        top: "-20px",
        right: "40px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "noorart",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Wall Art & Print",
    industryBadgeClass: "badge-retail",
    listTitle: "Canvas bot with Pinterest search — find and order artwork without leaving WhatsApp",
    listExcerpt: "Customers describe a vibe or theme; the bot returns matching visuals, captures size and material, then confirms the print order.",
    metrics: [
      {
        value: "Pinterest",
        label: "Live search in WA",
        color: "purple"
      },
      {
        value: "↑ 70%",
        label: "Order completion",
        color: "green"
      }
    ],
    tags: [
      "Pinterest API",
      "Print Orders"
    ],
    logoInitials: "NA",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/noorart.jpg",
    coverBg: "linear-gradient(135deg,#0f0a1a,#1e1035,#0f0a1a)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-20px",
        left: "60px",
        width: "120px",
        height: "120px"
      }
    ]
  },
  {
    id: "areef",
    category: "education",
    featuredWhenAll: true,
    industryLabel: "EdTech Platform",
    industryBadgeClass: "badge-education",
    listTitle: "RAG-powered AI tutor — 15 Tawjihi subjects, 300+ lessons indexed",
    listExcerpt: "Students get instant, curriculum-accurate answers from an Arabic AI tutor with source citations — built on Next.js, Supabase, and pgvector.",
    metrics: [
      {
        value: "300+",
        label: "Lessons indexed",
        color: "purple"
      },
      {
        value: "15",
        label: "Tawjihi subjects",
        color: "green"
      }
    ],
    tags: [
      "RAG",
      "Next.js 15",
      "Supabase",
      "pgvector"
    ],
    logoInitials: "عف",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/areef.jpg",
    coverBg: "linear-gradient(135deg,#0a1020,#101a3a,#0a1020)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-40px",
        right: "80px",
        width: "160px",
        height: "160px"
      },
      {
        background: "#1D9E75",
        bottom: "-10px",
        left: "60px",
        width: "80px",
        height: "80px"
      }
    ]
  },
  {
    id: "mina",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Furniture",
    industryBadgeClass: "badge-retail",
    listTitle: "Showroom AI agent that pre-qualifies buyers by room type and budget",
    listExcerpt: "The AI presents collections by room, filters by style and budget, and books showroom visits — reducing no-shows.",
    metrics: [
      {
        value: "↓ 45%",
        label: "No-show rate",
        color: "amber"
      },
      {
        value: "↑ 52%",
        label: "Qualified visits",
        color: "green"
      }
    ],
    tags: [
      "Showroom Bot",
      "Booking",
      "Gulf"
    ],
    logoInitials: "MF",
    logoStyle: {
      background: "rgba(239,159,39,.2)",
      border: "1px solid rgba(239,159,39,.35)"
    },
    coverImage: "/cases/covers/mina.jpg",
    coverBg: "linear-gradient(135deg,#150f0a,#2a1e10,#150f0a)",
    coverShapes: [
      {
        background: "#EF9F27",
        top: "-15px",
        right: "45px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "zain",
    category: "shipping",
    featuredWhenAll: false,
    industryLabel: "Logistics",
    industryBadgeClass: "badge-shipping",
    listTitle: "Tracking bot answering 400+ weekly status inquiries with no human agent",
    listExcerpt: "Customers text a shipment number; the bot returns live status, ETA, and branch contact — instantly in Arabic.",
    metrics: [
      {
        value: "400+",
        label: "Weekly auto-replies",
        color: "purple"
      },
      {
        value: "100%",
        label: "No human needed",
        color: "green"
      }
    ],
    tags: [
      "Tracking Bot",
      "API Integration"
    ],
    logoInitials: "ZL",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/zain.jpg",
    coverBg: "linear-gradient(135deg,#0a0f15,#101828,#0a0f15)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-20px",
        right: "50px",
        width: "120px",
        height: "120px"
      }
    ]
  },
  {
    id: "hayat",
    category: "services",
    featuredWhenAll: false,
    industryLabel: "Healthcare",
    industryBadgeClass: "badge-healthcare",
    listTitle: "Patient intake bot routing to the right department in under 30 seconds",
    listExcerpt: "Patients describe symptoms in Arabic or English; the bot identifies the department, shows slots, and confirms the appointment.",
    metrics: [
      {
        value: "<30s",
        label: "Dept. routing time",
        color: "green"
      },
      {
        value: "5 depts",
        label: "One WhatsApp number",
        color: "purple"
      }
    ],
    tags: [
      "Multi-Dept.",
      "Bilingual",
      "Qatar"
    ],
    logoInitials: "HC",
    logoStyle: {
      background: "rgba(29,158,117,.2)",
      border: "1px solid rgba(29,158,117,.35)"
    },
    coverImage: "/cases/covers/hayat.jpg",
    coverBg: "linear-gradient(135deg,#0f1a1a,#103030,#0f1a1a)",
    coverShapes: [
      {
        background: "#1D9E75",
        top: "-15px",
        left: "55px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "bloom",
    category: "retail",
    featuredWhenAll: false,
    industryLabel: "Flowers & Gifts",
    industryBadgeClass: "badge-retail",
    listTitle: "Gift recommendation AI that increased average order value by 35%",
    listExcerpt: "Customers describe occasion and budget; the AI recommends bundles, message cards, and same-day delivery in Gulf Arabic.",
    metrics: [
      {
        value: "↑ 35%",
        label: "Avg. order value",
        color: "green"
      },
      {
        value: "Gulf AR",
        label: "Dialect-aware AI",
        color: "amber"
      }
    ],
    tags: [
      "Gift AI",
      "Gulf Arabic",
      "Saudi"
    ],
    logoInitials: "BL",
    logoStyle: {
      background: "rgba(29,158,117,.2)",
      border: "1px solid rgba(29,158,117,.35)"
    },
    coverImage: "/cases/covers/bloom.jpg",
    coverBg: "linear-gradient(135deg,#0f150f,#1a2a1a,#0f150f)",
    coverShapes: [
      {
        background: "#1D9E75",
        top: "-15px",
        right: "45px",
        width: "110px",
        height: "110px"
      }
    ]
  },
  {
    id: "sama",
    category: "real-estate",
    featuredWhenAll: false,
    industryLabel: "Real Estate",
    industryBadgeClass: "badge-real-estate",
    listTitle: "Facebook Ads → WhatsApp pipeline qualifying 500+ leads per month",
    listExcerpt: "Leads from ads land in WhatsApp. The AI qualifies by budget, visa status, and property type before any sales call.",
    metrics: [
      {
        value: "500+",
        label: "Leads/month qualified",
        color: "purple"
      },
      {
        value: "↑ 78%",
        label: "Qualified lead rate",
        color: "green"
      }
    ],
    tags: [
      "FB Ads",
      "Lead Pipeline",
      "Dubai"
    ],
    logoInitials: "SR",
    logoStyle: {
      background: "rgba(127,119,221,.2)",
      border: "1px solid rgba(127,119,221,.35)"
    },
    coverImage: "/cases/covers/sama.jpg",
    coverBg: "linear-gradient(135deg,#100a1a,#201535,#100a1a)",
    coverShapes: [
      {
        background: "#7F77DD",
        top: "-30px",
        right: "60px",
        width: "130px",
        height: "130px"
      }
    ]
  }
];

export const caseStudyDetails: Record<string, CaseStudyDetail> = {
  "blue-arrow": {
    "kicker": "Real Estate · Baghdad, Iraq",
    "title": "How a real estate firm closed 3x more property deals with an AI sales agent that never sleeps",
    "background": "The sales team receives dozens of property inquiries daily via WhatsApp and social channels. With a small team, following up with every lead manually was impossible — hot buyers were slipping through.",
    "challenges": [
      "Slow response time meant buyers moved to competitors",
      "Agents spent hours re-explaining the same property details",
      "No system to qualify budget or interest before a site visit",
      "Zero visibility into which leads were worth pursuing"
    ],
    "flow": [
      "WhatsApp inquiry arrives → the agent greets and opens a qualification conversation",
      "The bot asks budget range, property type, and preferred area",
      "Matches the lead to the best available property from the catalog",
      "Sends a formatted property card with photos, specs, price, and floor plan",
      "If interested, books a site visit and notifies the agent on Slack",
      "Lead data and conversation summary logged to Google Sheets automatically"
    ],
    "tags": [
      "WhatsApp",
      "GPT-4.1",
      "Lead Qualification",
      "Property Cards",
      "Booking",
      "Google Sheets"
    ],
    "metrics": [
      {
        "value": "↑ 68%",
        "label": "Lead response rate",
        "color": "green"
      },
      {
        "value": "70%",
        "label": "Less manual follow-up",
        "color": "amber"
      },
      {
        "value": "3x",
        "label": "More deals closed",
        "color": "purple"
      }
    ]
  },
  "itshare": {
    "kicker": "Education · Egypt (3 branches)",
    "title": "AI enrollment agent handling 200+ daily inquiries across 3 branches without schedule mix-ups",
    "background": "An academy offers IT training across three Egyptian branches plus online options. Students ask about schedules, prices, and enrollment via WhatsApp — admin staff were overwhelmed and occasionally gave wrong branch information.",
    "challenges": [
      "Students receiving the wrong branch schedule",
      "Manual lead collection from WhatsApp was inconsistent",
      "High inquiry volume with limited admin bandwidth",
      "No structured handoff from bot conversation to sales team"
    ],
    "flow": [
      "Student sends inquiry → the agent identifies branch by location or preference",
      "Presents course options relevant to interest and level",
      "Shares the correct branch schedule — isolated per branch",
      "Captures name, phone, and course interest into a structured lead form",
      "Hot leads flagged and sent to the enrollment team via notification",
      "Follow-up sequence triggered automatically if no response after 24 hours"
    ],
    "tags": [
      "WhatsApp",
      "GPT-4.1",
      "Arabic AI",
      "Lead Capture",
      "Branch Logic",
      "Enrollment"
    ],
    "metrics": [
      {
        "value": "200+",
        "label": "Daily inquiries handled",
        "color": "purple"
      },
      {
        "value": "↑ 45%",
        "label": "Lead capture rate",
        "color": "green"
      },
      {
        "value": "0",
        "label": "Branch mix-ups",
        "color": "amber"
      }
    ]
  },
  "givari": {
    "kicker": "eCommerce · Fashion · Iraq",
    "title": "Dual-agent fashion bot with WooCommerce and vision-based product lookup",
    "background": "A women's fashion retailer with a large WooCommerce catalog. Customers constantly sent product photos asking if items were in stock — staff spent hours manually searching the catalog.",
    "challenges": [
      "Customers sending photos that staff had to match manually",
      "Catalog too large to browse easily in conversation",
      "Sales and support journeys needed different tones",
      "High cart abandonment from ordering friction"
    ],
    "flow": [
      "Customer sends a product photo → vision AI analyzes and identifies the item",
      "Sales agent searches the catalog by visual match or product code",
      "Returns availability, price, sizes, and color options",
      "Customer confirms → agent guides through size selection and order",
      "Payment and delivery confirmed → order logged automatically",
      "Complaints or returns → support agent takes over with a different persona"
    ],
    "tags": [
      "WooCommerce API",
      "GPT-4 Vision",
      "Dual Agent",
      "WhatsApp",
      "Fashion"
    ],
    "metrics": [
      {
        "value": "↑ 55%",
        "label": "Orders via WhatsApp",
        "color": "green"
      },
      {
        "value": "0",
        "label": "Manual lookups needed",
        "color": "amber"
      },
      {
        "value": "↑ 28%",
        "label": "Avg. basket size",
        "color": "purple"
      }
    ]
  },
  "waseem": {
    "kicker": "ISP & Services · Iraq",
    "title": "Separate AI agents for sales and technical support on one WhatsApp number",
    "background": "An ISP sells internet plans across Baghdad. One WhatsApp inbox mixed upgrade requests with outage complaints — handled by the same team, creating confusion.",
    "challenges": [
      "Sales and support conversations mixed in one inbox",
      "Support staff accidentally upselling during outage complaints",
      "No systematic way to resolve common technical issues",
      "Agents context-switching constantly"
    ],
    "flow": [
      "Customer messages → intent classifier determines sales or support",
      "Sales agent presents plans, compares speeds, processes upgrades",
      "Support agent runs diagnostic checklist, resolves most issues",
      "Unresolved issues escalated to human with full context summary",
      "Sales agent may offer plan upgrades after support resolution",
      "All conversations tagged and logged for weekly reporting"
    ],
    "tags": [
      "Dual Agent",
      "Intent Classification",
      "ISP",
      "Sales Bot",
      "Support Bot"
    ],
    "metrics": [
      {
        "value": "80%",
        "label": "Support tickets auto-resolved",
        "color": "green"
      },
      {
        "value": "↑ 40%",
        "label": "Upsell conversion",
        "color": "purple"
      },
      {
        "value": "↓ 65%",
        "label": "Human escalations",
        "color": "amber"
      }
    ]
  },
  "sultan": {
    "kicker": "Shipping & Logistics · Southern Iraq",
    "title": "Automated shipment booking from WhatsApp inquiry to confirmation in under 2 minutes",
    "background": "A logistics company handles inter-city shipments. Each booking used to require phone calls, manual spreadsheet entry, and a confirmation call — taking 15–20 minutes per order.",
    "challenges": [
      "Every booking required staff on the phone for 15+ minutes",
      "Manual spreadsheet entry caused errors",
      "No confirmation system for customers after booking",
      "Staff capacity limited daily order volume"
    ],
    "flow": [
      "Customer sends shipping request → bot collects origin, destination, weight, and type",
      "Calculates cost automatically based on route and weight table",
      "Presents quote and confirms with customer",
      "On confirmation: creates row in Google Sheets and assigns tracking ID",
      "Sends confirmation with tracking ID and estimated pickup time",
      "Daily summary sheet generated for the dispatch team"
    ],
    "tags": [
      "WhatsApp",
      "Google Sheets",
      "Shipping",
      "Order Bot",
      "Automation"
    ],
    "metrics": [
      {
        "value": "↓ 85%",
        "label": "Manual data entry",
        "color": "amber"
      },
      {
        "value": "<2 min",
        "label": "Booking time",
        "color": "green"
      },
      {
        "value": "↑ 3x",
        "label": "Daily order capacity",
        "color": "purple"
      }
    ]
  },
  "rz-estate": {
    "kicker": "Real Estate · Kurdistan Region",
    "title": "Trilingual AI agent unlocking international property inquiries around the clock",
    "background": "A real estate firm serves buyers from Iraq, the Gulf, and diaspora communities. Inquiries arrived in Arabic, Kurdish Sorani, and English — the team could only respond confidently in one language.",
    "challenges": [
      "Sorani-speaking buyers receiving Arabic-only responses",
      "English-speaking diaspora buyers with no follow-up in their language",
      "No qualification system across three buyer segments",
      "Agents unavailable after hours for international time zones"
    ],
    "flow": [
      "Inquiry arrives → agent detects language from the first message",
      "Responds in the detected language throughout",
      "Qualifies by property type, budget, and timeline",
      "Presents matched property cards in the buyer's language",
      "Books a callback with the appropriate bilingual agent",
      "Lead profile with language flag sent to CRM"
    ],
    "tags": [
      "Multilingual AI",
      "Kurdish Sorani",
      "Arabic",
      "English",
      "Real Estate",
      "Lead Routing"
    ],
    "metrics": [
      {
        "value": "3 langs",
        "label": "Arabic · Sorani · EN",
        "color": "purple"
      },
      {
        "value": "↑ 60%",
        "label": "International conversion",
        "color": "green"
      },
      {
        "value": "24/7",
        "label": "Response coverage",
        "color": "amber"
      }
    ]
  },
  "mimi": {
    "kicker": "Fashion Retail · Iraq",
    "title": "AI shopping assistant that boosted repeat purchase rate for a women's fashion brand",
    "background": "A fashion retailer with a loyal WhatsApp customer base. Customers expected personalized service — size memory and past orders — but the team could not maintain that manually at scale.",
    "challenges": [
      "Staff forgetting customer size preferences",
      "Generic broadcast messages getting ignored",
      "High repeat inquiries for size and availability",
      "No proactive surfacing of new arrivals to the right customers"
    ],
    "flow": [
      "Returning customer messages → bot retrieves purchase history",
      "Greets by name and references last purchase context",
      "Recommends new arrivals matching past preferences and budget",
      "Handles size inquiries with stored measurements",
      "Processes order with address and payment preference from profile",
      "Sends styled outfit suggestion as follow-up after delivery"
    ],
    "tags": [
      "Personalization",
      "Customer History",
      "Fashion Bot",
      "WhatsApp",
      "Repeat Sales"
    ],
    "metrics": [
      {
        "value": "↑ 38%",
        "label": "Repeat purchase rate",
        "color": "green"
      },
      {
        "value": "92%",
        "label": "CSAT score",
        "color": "amber"
      },
      {
        "value": "↑ 25%",
        "label": "Avg. order value",
        "color": "purple"
      }
    ]
  },
  "dr-ihab": {
    "kicker": "Healthcare · Orthopedic clinic · Iraq",
    "title": "Appointment bot handling booking, rescheduling, and cancellations 24/7 in Arabic",
    "background": "A busy orthopedic clinic handles high patient volume. The front desk was overwhelmed with appointment calls, and many patients called outside working hours with no response.",
    "challenges": [
      "Patients calling outside hours with no way to book",
      "Front desk spending much of the day on appointment calls",
      "High no-show rate without automated reminders",
      "Manual appointment book with no conflict checking"
    ],
    "flow": [
      "Patient sends WhatsApp message → bot identifies new or returning patient",
      "Presents available slots for the next 7 days",
      "Patient selects slot → bot confirms and logs appointment",
      "Automated reminder sent 24 hours before appointment",
      "Day-of reminder with clinic location details",
      "Cancellation or reschedule handled in chat, slot freed instantly"
    ],
    "tags": [
      "Appointment Bot",
      "Healthcare",
      "Arabic",
      "Reminders",
      "Scheduling"
    ],
    "metrics": [
      {
        "value": "↓ 60%",
        "label": "Front-desk calls",
        "color": "green"
      },
      {
        "value": "24/7",
        "label": "Booking availability",
        "color": "purple"
      },
      {
        "value": "↓ 30%",
        "label": "No-show rate",
        "color": "amber"
      }
    ]
  },
  "panda": {
    "kicker": "eCommerce · Tech Accessories · Iraq",
    "title": "AI product advisor automating 80% of customer conversations for a tech accessories store",
    "background": "A tech accessories store gets constant compatibility questions like whether a case fits a specific phone model — requiring product knowledge staff could not always answer quickly.",
    "challenges": [
      "High volume of device compatibility questions",
      "Customers leaving without buying when no one answered in time",
      "No system to recommend complementary accessories at inquiry",
      "Inconsistent product knowledge across support staff"
    ],
    "flow": [
      "Customer asks about compatibility → agent identifies device model",
      "Checks compatibility database and confirms fit or suggests variant",
      "Presents product with price, availability, and shipping time",
      "Recommends complementary accessories bundle",
      "Processes order with address and payment method",
      "Sends tracking update when shipped"
    ],
    "tags": [
      "Tech Accessories",
      "Compatibility AI",
      "Cross-sell",
      "WhatsApp",
      "Order Bot"
    ],
    "metrics": [
      {
        "value": "↓ 50%",
        "label": "Support tickets",
        "color": "green"
      },
      {
        "value": "80%",
        "label": "Fully automated",
        "color": "amber"
      },
      {
        "value": "↑ 35%",
        "label": "Cross-sell rate",
        "color": "purple"
      }
    ]
  },
  "villa": {
    "kicker": "Retail · Baghdad, Iraq",
    "title": "Conversational sales agent that turned WhatsApp into the store's top revenue channel",
    "background": "A Baghdad retail store had strong walk-in traffic but informal WhatsApp usage — inquiries went cold when staff replied late.",
    "challenges": [
      "Informal WhatsApp responses with hours of delay",
      "No catalog presentation — staff typed details manually",
      "Customers asking prices then going silent",
      "No data on which products drove most inquiries"
    ],
    "flow": [
      "Customer messages → agent greets in Iraqi Arabic dialect",
      "Presents product categories with visual descriptions",
      "Customer selects interest → agent shares price, availability, colors",
      "Handles objections and suggests alternatives",
      "Closes sale with delivery or pickup confirmation",
      "Post-sale follow-up at 24h and 72h intervals"
    ],
    "tags": [
      "Sales Agent",
      "Iraqi Arabic Dialect",
      "Retail",
      "WhatsApp",
      "Catalog Bot"
    ],
    "metrics": [
      {
        "value": "↑ 42%",
        "label": "WhatsApp revenue",
        "color": "amber"
      },
      {
        "value": "3 min",
        "label": "Avg. close time",
        "color": "green"
      },
      {
        "value": "60 days",
        "label": "To top channel",
        "color": "purple"
      }
    ]
  },
  "noor": {
    "kicker": "Print & Education · Southern Iraq",
    "title": "Automated curriculum book sales during peak school season with zero entry errors",
    "background": "A print house sells curriculum books to schools and families each academic year. During back-to-school season, orders flooded WhatsApp — each requiring manual entry and confirmation.",
    "challenges": [
      "Hundreds of orders in the first two weeks of school season",
      "Manual order entry creating wrong grade combinations",
      "No confirmation sent to customers after ordering",
      "Staff overwhelmed leading to delayed responses"
    ],
    "flow": [
      "Parent or teacher messages → bot asks school level and grade",
      "Presents correct book bundle for that grade",
      "Confirms quantities and subject additions",
      "Calculates total price and confirms payment method",
      "Order logged to Google Sheets with customer info",
      "Pickup confirmation with date and location sent automatically"
    ],
    "tags": [
      "Book Sales",
      "Curriculum Bot",
      "Seasonal Automation",
      "WhatsApp",
      "Google Sheets"
    ],
    "metrics": [
      {
        "value": "300+",
        "label": "Peak season orders",
        "color": "purple"
      },
      {
        "value": "0",
        "label": "Entry errors",
        "color": "green"
      },
      {
        "value": "↓ 90%",
        "label": "Admin time on orders",
        "color": "amber"
      }
    ]
  },
  "fofa": {
    "kicker": "Fashion Retail · Iraq",
    "title": "One AI agent managing two women's fashion brands from a single WhatsApp number",
    "background": "Two clothing brands run by the same owner used separate WhatsApp numbers — splitting workload and confusing loyal customers.",
    "challenges": [
      "Two separate numbers creating operational overhead",
      "Customers unsure which number handles which brand",
      "No way to cross-sell between brands",
      "Inconsistent tone and response time across accounts"
    ],
    "flow": [
      "Customer messages shared number → bot identifies which brand they mean",
      "Presents relevant brand catalog with appropriate tone",
      "If inquiry fits both brands, suggests the other option",
      "Handles size, availability, and pricing per brand",
      "Order processed with brand-specific delivery details",
      "Cross-brand recommendation when relevant"
    ],
    "tags": [
      "Multi-Brand",
      "Fashion Bot",
      "Iraqi Arabic",
      "Single Inbox",
      "Cross-sell"
    ],
    "metrics": [
      {
        "value": "2 brands",
        "label": "One WhatsApp number",
        "color": "purple"
      },
      {
        "value": "↑ 33%",
        "label": "Cross-brand sales",
        "color": "green"
      },
      {
        "value": "0",
        "label": "Brand mix-up incidents",
        "color": "amber"
      }
    ]
  },
  "amcupcakes": {
    "kicker": "Food & Bakery · Cairo, Egypt",
    "title": "WhatsApp ordering bot that doubled weekend capacity and eliminated phone orders",
    "background": "A Cairo bakery had a cult following but took all orders by phone. On weekends the phone rang non-stop and orders got mixed up.",
    "challenges": [
      "Manual phone orders collapsing on busy weekends",
      "Order mix-ups from verbal confirmations",
      "No upselling — customers only ordered what they called about",
      "No visibility into upcoming order volume for production"
    ],
    "flow": [
      "Customer messages → bot presents menu with photos and prices",
      "Flavor and quantity selection with customization options",
      "Delivery slot selection from available times",
      "Upsell prompt for card message or gift box",
      "Order total confirmed with payment instructions",
      "Order added to production sheet with delivery time"
    ],
    "tags": [
      "Food Ordering",
      "WhatsApp",
      "Menu Bot",
      "Delivery Slots",
      "Egypt",
      "Bakery"
    ],
    "metrics": [
      {
        "value": "↑ 2x",
        "label": "Weekend order capacity",
        "color": "coral"
      },
      {
        "value": "0",
        "label": "Phone orders needed",
        "color": "green"
      },
      {
        "value": "↑ 28%",
        "label": "Avg. order value",
        "color": "amber"
      }
    ]
  },
  "noorart": {
    "kicker": "Wall Art & Custom Print · Iraq",
    "title": "Pinterest-powered canvas ordering inside WhatsApp",
    "background": "A custom canvas studio prints art in Iraq. Customers struggled to describe what they wanted and were sent to browse Pinterest themselves — a broken experience.",
    "challenges": [
      "Customers struggling to describe what they wanted clearly",
      "Long back-and-forth to clarify design references",
      "No structured capture of canvas size and material preferences",
      "High drop-off when asked to send Pinterest links manually"
    ],
    "flow": [
      "Customer describes vibe or theme (e.g. modern Arabic calligraphy)",
      "Bot queries Pinterest API and returns matching images in chat",
      "Customer picks favorite → bot confirms canvas size options",
      "Material selection: matte, glossy, or framed",
      "Price calculated based on size and material",
      "Order confirmed with delivery time and payment details"
    ],
    "tags": [
      "Pinterest API",
      "Canvas Printing",
      "Custom Orders",
      "WhatsApp",
      "Visual Search"
    ],
    "metrics": [
      {
        "value": "Pinterest",
        "label": "Live search in WhatsApp",
        "color": "purple"
      },
      {
        "value": "↑ 70%",
        "label": "Order completion rate",
        "color": "green"
      },
      {
        "value": "0",
        "label": "Website visits needed",
        "color": "amber"
      }
    ]
  },
  "areef": {
    "kicker": "EdTech Platform · Palestinian Tawjihi",
    "title": "Full-stack RAG educational platform with an Arabic AI tutor for Tawjihi students",
    "background": "Palestinian Tawjihi students had limited access to quality tutoring. The platform was built using RAG to answer curriculum-accurate questions in Arabic from indexed lesson content.",
    "challenges": [
      "Building curriculum-accurate AI that avoids hallucinating exam answers",
      "Structuring 300+ lessons from 15 subjects into a vector database",
      "Arabic RTL rendering across all UI components",
      "Keeping API costs manageable for a student-facing platform"
    ],
    "flow": [
      "Student logs in and selects subject",
      "Types a question in Arabic → system embeds and queries pgvector",
      "Retrieves relevant lesson chunks from Supabase",
      "GPT-4 generates answer grounded in context with citation",
      "Follow-up questions maintain session context",
      "Admin uploads new lessons → auto-embedded and indexed"
    ],
    "tags": [
      "RAG",
      "pgvector",
      "Next.js 15",
      "Supabase",
      "OpenAI",
      "Arabic AI",
      "Education"
    ],
    "metrics": [
      {
        "value": "300+",
        "label": "Lessons indexed",
        "color": "purple"
      },
      {
        "value": "15",
        "label": "Tawjihi subjects",
        "color": "green"
      },
      {
        "value": "pgvector",
        "label": "RAG architecture",
        "color": "amber"
      }
    ]
  },
  "mina": {
    "kicker": "Furniture & Interior · Gulf Region",
    "title": "Showroom AI agent that pre-qualifies furniture buyers before they visit",
    "background": "A Gulf furniture retailer receives showroom visit requests via WhatsApp. Many visitors arrived without clear budget or decision-making authority.",
    "challenges": [
      "High no-show rate from unqualified leads",
      "Sales team spending equal time on browsers and buyers",
      "No pre-visit qualification to match inventory",
      "Inconsistent follow-up after visit requests"
    ],
    "flow": [
      "Customer expresses interest in visiting → qualification conversation",
      "Identifies room(s) to furnish and approximate budget",
      "Presents relevant collections for their criteria",
      "Confirms visit time slot in the system",
      "Sends pre-visit prep: what to measure and parking info",
      "Post-visit follow-up at 24h and 72h"
    ],
    "tags": [
      "Showroom Bot",
      "Furniture",
      "Lead Qualification",
      "Booking",
      "Gulf",
      "WhatsApp"
    ],
    "metrics": [
      {
        "value": "↓ 45%",
        "label": "No-show rate",
        "color": "amber"
      },
      {
        "value": "↑ 52%",
        "label": "Qualified showroom visits",
        "color": "green"
      },
      {
        "value": "3 min",
        "label": "Qualification time",
        "color": "purple"
      }
    ]
  },
  "zain": {
    "kicker": "Logistics & Tracking · Iraq",
    "title": "Real-time shipment tracking bot handling 400+ weekly inquiries automatically",
    "background": "A logistics company handles inter-city shipments. The biggest WhatsApp volume was 'where is my package?' — answered hundreds of times per week manually.",
    "challenges": [
      "Staff answering the same tracking question repeatedly",
      "API data available but not integrated with WhatsApp",
      "Customers calling outside hours with no self-serve option",
      "No escalation path for genuinely stuck shipments"
    ],
    "flow": [
      "Customer sends shipment ID",
      "Bot queries tracking API in real time",
      "Returns status, last checkpoint, ETA, and branch contact",
      "If delayed → explains why and gives new ETA",
      "If problem reported → escalates to human with full context",
      "All queries logged for delay pattern analysis"
    ],
    "tags": [
      "Tracking Bot",
      "Logistics",
      "API Integration",
      "WhatsApp",
      "Automation"
    ],
    "metrics": [
      {
        "value": "400+",
        "label": "Weekly auto-replies",
        "color": "purple"
      },
      {
        "value": "100%",
        "label": "No human needed",
        "color": "green"
      },
      {
        "value": "↓ 80%",
        "label": "Support load",
        "color": "amber"
      }
    ]
  },
  "hayat": {
    "kicker": "Healthcare · Multi-dept. clinic · Qatar",
    "title": "One WhatsApp number routing patients to the right specialist in under 30 seconds",
    "background": "A Doha clinic has five departments. Patients often did not know which department they needed — causing misdirected bookings.",
    "challenges": [
      "Patients unsure which department handles their symptoms",
      "Misdirected bookings wasting specialist slots",
      "Bilingual patient base with inconsistent handling",
      "High no-show rate due to location confusion in the clinic"
    ],
    "flow": [
      "Patient describes symptoms or mentions specialty",
      "AI classifies the correct department",
      "Confirms in patient's language",
      "Shows available slots for that department",
      "Booking confirmed → calendar entry created",
      "Reminder sent 24h before with floor and what to bring",
      "Missed appointment → bot follows up to reschedule"
    ],
    "tags": [
      "Multi-Department",
      "Healthcare",
      "Bilingual",
      "Arabic",
      "English",
      "Qatar",
      "Booking Bot"
    ],
    "metrics": [
      {
        "value": "<30s",
        "label": "Routing time",
        "color": "green"
      },
      {
        "value": "5 depts",
        "label": "One WhatsApp number",
        "color": "purple"
      },
      {
        "value": "↓ 55%",
        "label": "Misdirected bookings",
        "color": "amber"
      }
    ]
  },
  "bloom": {
    "kicker": "Flowers & Gifts · Riyadh, Saudi Arabia",
    "title": "Gift recommendation AI that increased average order value by 35%",
    "background": "A Riyadh florist targets premium gifting. Customers expected consultative service for occasions, not just a product catalog.",
    "challenges": [
      "Customers asking for recommendations with no clear answer path",
      "Gulf Arabic dialect expected — formal Arabic felt off-brand",
      "No structured bundle-building",
      "Same-day delivery slots filling up from late orders"
    ],
    "flow": [
      "Customer describes occasion and recipient",
      "Bot asks budget range and delivery urgency",
      "Recommends three curated bundles with descriptions",
      "Add-ons: personalized card, luxury wrap, chocolate box",
      "Customer picks bundle → delivery slot from live availability",
      "Order confirmed with delivery window and driver contact"
    ],
    "tags": [
      "Gulf Arabic",
      "Gift AI",
      "Flowers",
      "Luxury Retail",
      "Saudi Arabia",
      "Same-day Delivery"
    ],
    "metrics": [
      {
        "value": "↑ 35%",
        "label": "Avg. order value",
        "color": "green"
      },
      {
        "value": "Gulf AR",
        "label": "Dialect-native AI",
        "color": "amber"
      },
      {
        "value": "↑ 48%",
        "label": "Same-day delivery rate",
        "color": "purple"
      }
    ]
  },
  "sama": {
    "kicker": "Real Estate · Dubai, UAE",
    "title": "Facebook Ads to WhatsApp pipeline qualifying 500+ leads per month on autopilot",
    "background": "A Dubai real estate firm runs Facebook ad campaigns. Leads clicked through to WhatsApp with no qualification — agents called hundreds of unqualified contacts monthly.",
    "challenges": [
      "Agents wasting time on leads with unrealistic budgets",
      "No standardized qualification before first sales call",
      "High cost per qualified lead from manual filtering",
      "Leads going cold between ad click and first call"
    ],
    "flow": [
      "Facebook ad click → WhatsApp opens with property interest",
      "Bot greets in under 5 seconds",
      "Qualifies: budget, timeline, residency status, property type",
      "Hot leads → instant callback booking with an agent",
      "Warm leads → nurture sequence with market updates",
      "Cold leads → tagged in CRM, removed from agent pipeline"
    ],
    "tags": [
      "Facebook Ads",
      "Lead Pipeline",
      "Dubai",
      "Real Estate",
      "Qualification",
      "CRM Integration"
    ],
    "metrics": [
      {
        "value": "500+",
        "label": "Leads/month qualified",
        "color": "purple"
      },
      {
        "value": "↑ 78%",
        "label": "Qualified lead rate",
        "color": "green"
      },
      {
        "value": "↓ 70%",
        "label": "Cost per qualified lead",
        "color": "amber"
      }
    ]
  }
};

export function getCaseById(id: string): CaseStudy | null {
  const card = caseIndexCards.find((c) => c.id === id);
  const detail = caseStudyDetails[id];
  if (!card || !detail) return null;
  return { ...card, detail };
}

export function getAllCaseIds(): string[] {
  return caseIndexCards.map((c) => c.id);
}

export const caseIndexFilters: { id: CaseIndexCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "real-estate", label: "Real Estate" },
  { id: "education", label: "Education" },
  { id: "ecommerce", label: "eCommerce" },
  { id: "services", label: "Services" },
  { id: "shipping", label: "Shipping" },
  { id: "retail", label: "Retail" },
  { id: "food", label: "Food & Bakery" },
  { id: "print", label: "Print & Media" },
];

export const caseIndexStats = [
  { num: "40", suffix: "+", label: "Active clients" },
  { num: "8", suffix: "", label: "Industries" },
  { num: "3", suffix: "x", label: "Avg. response lift" },
  { num: "24", suffix: "/7", label: "Bot uptime" },
];
