export type HomeLang = "en" | "ar";

export const homeLandingCopy = {
  en: {
    navLinks: ["Home", "Features", "Integration", "Pricing", "Automation", "Cases", "Academy"],
    badge:
      "Now live — Build your AI agent today",
    hl1: "Your business deserves",
    hl2: "a smarter agent",
    hl3Before: "not just a ",
    hl3Accent: "chatbot",
    sub: "Build a bilingual AI agent for your business in minutes. No code. No complexity. Just results — in Arabic & English.",
    cta1t: "Build your agent free",
    cta2t: "See how it works",
    t1: "No credit card",
    t2: "Arabic + English",
    t3: "Live in minutes",
    s1: "Clients",
    s2: "Industries",
    s3: "Countries",
    probLabel: "The problem we solve",
    probTitleBefore: "From pain points to ",
    probTitleSpan: "real results",
    beforeLbl: "Before Samy",
    afterLbl: "After Samy",
    p1: "Missing customer messages after hours",
    p2: "Team overwhelmed with repetitive questions",
    p3: "Lost sales from slow response times",
    sol1: "AI replies instantly, 24/7, in any language",
    sol2: "Agent handles 80% of inquiries automatically",
    sol3: "Convert visitors into customers instantly",
    featLabel: "What you get",
    featTitleBefore: "Built for ",
    featTitleSpan: "real businesses",
    f1t: "24/7 Availability",
    f1d: "Your agent never sleeps. Handles every inquiry around the clock without breaks.",
    f2t: "Arabic + English",
    f2d: "Fully bilingual. Switches language automatically based on the customer.",
    f3t: "Multi-Channel",
    f3d: "WhatsApp, Instagram, Messenger — one agent across all your channels.",
    f4t: "Smart Handoff",
    f4d: "Seamlessly transfers complex cases to your human team — no friction.",
    featSeeAll: "See all features",
    indLabel: "Who we work with",
    indTitleBefore: "Built for ",
    indTitleSpan: "every industry",
    testiLabel: "What clients say",
    testiTitleBefore: "Trusted by ",
    testiTitleSpan: "real businesses",
    urgencyTxt: "Only 3 new clients this month",
    ctaHlBefore: "Get ahead before ",
    ctaHlSpan: "your competitors do",
    ctaSub: "Your AI agent, live in 7 days. No tech headaches. No long contracts.",
    ctaB1: "Build your agent free",
    ctaB2: "WhatsApp us",
    tc1: "No contracts",
    tc2: "Ongoing support",
    tc3: "Results or refund",
    btnBuild: "Build Agent",
    footTagline: "AI-powered agents for businesses that move fast. Arabic & English.",
    footGetInTouch: "Get in touch",
    footGetInTouchSub: "Have a custom project in mind? Let's talk.",
    footWhatsApp: "WhatsApp →",
    copy: "© 2025 Samy — AI Chatbot Agency",
    privacy: "Privacy",
    terms: "Terms",
    product: "Product",
    resources: "Resources",
    retail: "Retail",
    medical: "Medical",
    education: "Education",
    realEstate: "Real Estate",
    services: "Services",
    indRetailDesc: "Product inquiries, orders, and after-sales support automated.",
    indMedicalDesc: "Appointment booking, pre-screening, and patient FAQs.",
    indReDesc: "Property listings, viewing scheduling, and lead qualification.",
    indServDesc: "Quote requests, booking flows, and customer follow-up.",
    indEduDesc: "Course info, enrollment support, and student Q&A 24/7.",
    casesLink: "→ Cases",
    learnMore: "→ Learn more",
    testi1:
      "The agent handles 90% of our Instagram inquiries automatically. Our team finally has time to focus on real work.",
    testi2:
      "Setup was incredibly fast. The bot understands Iraqi dialect and handles orders without any human help.",
    testi3:
      "Our clinic reduced missed appointments by 60%. Patients book and get reminders all through WhatsApp.",
    chips: ["Retail", "Medical", "Education", "Real Estate", "Services"],
    footLinkFeatures: "Features",
    footLinkIntegration: "Integration",
    footLinkPricing: "Pricing",
    footLinkAutomation: "Automation",
    footLinkAcademy: "Academy",
    footLinkCases: "Cases",
    footLinkBlog: "Blog",
    footLinkKnowledgeBase: "Knowledge Base",
    footLinkSupport: "Support",
    footLinkApi: "API Docs",
  },
  ar: {
    navLinks: ["الرئيسية", "المميزات", "التكاملات", "الأسعار", "أتمتة", "قصص النجاح", "الأكاديمية"],
    badge: "متاح الآن — ابني أجنتك الذكي اليوم",
    hl1: "عملك يستحق",
    hl2: "أجنت أذكى",
    hl3Before: "مش مجرد ",
    hl3Accent: "شات بوت",
    sub: "ابني أجنت ذكي لعملك في دقائق. بدون كود. بدون تعقيد. نتائج حقيقية — بالعربي والإنجليزي.",
    cta1t: "ابني أجنتك مجاناً",
    cta2t: "شوف كيف يشتغل",
    t1: "بدون بطاقة بنكية",
    t2: "عربي + إنجليزي",
    t3: "شغال في دقائق",
    s1: "عميل",
    s2: "صناعة",
    s3: "دول",
    probLabel: "المشكلة اللي نحلها",
    probTitleBefore: "من المشاكل إلى ",
    probTitleSpan: "نتائج حقيقية",
    beforeLbl: "قبل Samy",
    afterLbl: "بعد Samy",
    p1: "رسائل العملاء بتضيع بعد وقت الدوام",
    p2: "الفريق مرهق من الأسئلة المتكررة",
    p3: "مبيعات ضايعة بسبب بطء الرد",
    sol1: "الأجنت يرد فوراً، 24/7، بأي لغة",
    sol2: "الأجنت بيتعامل مع 80% من الاستفسارات تلقائياً",
    sol3: "حول الزوار لعملاء في ثوانٍ",
    featLabel: "إيه اللي هتاخده",
    featTitleBefore: "مصمم لـ ",
    featTitleSpan: "بيزنس حقيقي",
    f1t: "متاح 24/7",
    f1d: "الأجنت مش بينام. بيتعامل مع كل استفسار على مدار الساعة.",
    f2t: "عربي + إنجليزي",
    f2d: "ثنائي اللغة بالكامل. بيتحول تلقائياً حسب العميل.",
    f3t: "متعدد القنوات",
    f3d: "واتساب، انستجرام، ماسنجر — أجنت واحد على كل القنوات.",
    f4t: "تسليم ذكي",
    f4d: "بينقل الحالات المعقدة لفريقك البشري بدون احتكاك.",
    featSeeAll: "كل المميزات",
    indLabel: "مع مين بنشتغل",
    indTitleBefore: "مصمم لـ ",
    indTitleSpan: "كل صناعة",
    testiLabel: "إيه اللي بيقوله العملاء",
    testiTitleBefore: "موثوق من ",
    testiTitleSpan: "بيزنسات حقيقية",
    urgencyTxt: "نقبل 3 عملاء جدد هذا الشهر فقط",
    ctaHlBefore: "خليك جاهز ",
    ctaHlSpan: "قبل منافسيك",
    ctaSub: "أجنتك الذكي جاهز في 7 أيام. بدون تعقيد. بدون عقود.",
    ctaB1: "ابني أجنتي مجاناً",
    ctaB2: "تواصل واتساب",
    tc1: "بدون عقود",
    tc2: "دعم مستمر",
    tc3: "نتيجة أو استرداد",
    btnBuild: "ابني وكيلك",
    footTagline: "أجنت ذكي للشركات السريعة. عربي وإنجليزي.",
    footGetInTouch: "تواصل معنا",
    footGetInTouchSub: "مشروع مخصص؟ نسعد نتكلم.",
    footWhatsApp: "واتساب ←",
    copy: "© 2025 Samy — AI Chatbot Agency",
    privacy: "الخصوصية",
    terms: "الشروط",
    product: "المنتج",
    resources: "الموارد",
    retail: "تجارة",
    medical: "طبي",
    education: "تعليم",
    realEstate: "عقارات",
    services: "خدمات",
    indRetailDesc: "استفسارات المنتجات، الطلبات، وخدمة ما بعد البيع تلقائياً.",
    indMedicalDesc: "حجز المواعيد، الفحص المسبق، وأسئلة المرضى.",
    indReDesc: "قوائم العقارات وجدولة المعاينات وتأهيل العملاء.",
    indServDesc: "طلبات عروض الأسعار وحجوزات ومتابعة العملاء.",
    indEduDesc: "معلومات الدورات والتسجيل وأسئلة الطلاب 24/7.",
    casesLink: "← قصص النجاح",
    learnMore: "← اعرف أكثر",
    testi1:
      "الأجنت يتعامل مع 90% من استفسارات الانستجرام تلقائياً. الفريق بدأ يشتغل على الشغل الحقيقي.",
    testi2: "التجهيز كان سريع جداً. البوت يفهم لهجة العراقي وبياخد الطلبات بدون تدخل بشري.",
    testi3:
      "عيادتنا قلّلنا المواعيد الفائتة بحوالي 60%. المرضى يحجزوا ويوصلهم تذكير على الواتساب.",
    chips: ["تجارة", "طبي", "تعليم", "عقارات", "خدمات"],
    footLinkFeatures: "المميزات",
    footLinkIntegration: "التكاملات",
    footLinkPricing: "الأسعار",
    footLinkAutomation: "الأتمتة",
    footLinkAcademy: "الأكاديمية",
    footLinkCases: "قصص النجاح",
    footLinkBlog: "المدونة",
    footLinkKnowledgeBase: "قاعدة المعرفة",
    footLinkSupport: "الدعم",
    footLinkApi: "واجهة API",
  },
};
